---

- name: establish package
  become: true
  package:
    name: snapd
    state: present
  notify: enable snapd service
  tags: install

- name: establish configuration directory
  become: true
  file:
    path: "{{ snapd_configuration_file_path | dirname }}"
    state: directory
  tags: install, configure

- name: establish configuration
  when: snapd_configuration is defined
  become: true
  template:
    src: snapd.conf.j2
    dest: "{{ snapd_configuration_file_path }}"
    mode: "u=rw,go=r"
  notify: restart snapd
  tags: configure
